# Generated by Django 3.2.5 on 2021-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210713_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='imagen_problema',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
