# Generated by Django 3.2.5 on 2021-07-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trabajo_imagen_problema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='nuevo',
        ),
    ]
