# Generated by Django 3.2.5 on 2021-07-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trabajo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='imagen_problema',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
